import Link from "next/link";
import { ArrowLeft, FileText, Scale, AlertCircle, CheckCircle, Shield, ShieldAlert, BookOpen } from "lucide-react";

export const metadata = {
  title: "Terms of Service | Audia",
  description: "Read Audia's Terms of Service — covering user responsibilities, fair use, content ingestion, and limitation of liability.",
};

const sections = [
  {
    icon: CheckCircle,
    title: "1. Acceptance of Terms",
    body: [
      "By accessing or using Audia (the \u201cService\u201d), you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree with any part of these terms, you may not access the Service.",
      "We may update these Terms at any time. Continued use of the Service after changes are posted constitutes your acceptance of the revised Terms. We will make reasonable efforts to notify registered users of material changes via email or in-app notice.",
    ],
  },
  {
    icon: FileText,
    title: "2. User Responsibilities",
    body: [
      "You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You agree to notify us immediately of any unauthorised access.",
      "You must be at least 13 years of age to use the Service (or the minimum age required in your jurisdiction). By registering, you represent and warrant that you meet this requirement.",
      "You agree to use the Service only for lawful purposes and in a manner consistent with these Terms, all applicable laws, and the rights of third parties.",
    ],
  },
  {
    icon: AlertCircle,
    title: "3. Prohibited Activities",
    body: [
      "You may not: (a) use the Service to infringe, misappropriate, or violate any intellectual property or other rights of any third party; (b) redistribute AI-generated summaries commercially without written permission; (c) attempt to reverse-engineer, scrape, or extract our proprietary models or algorithms; (d) use automated systems or bots to abuse rate limits or access controls; (e) resell or sub-license access to your account; or (f) upload or transmit malware, viruses, or any code designed to disrupt the Service.",
    ],
  },
  {
    icon: BookOpen,
    title: "4. Content Ingestion & Fair Use",
    body: [
      "Audia is a user-directed tool. When you provide a URL or RSS feed, you represent and warrant that you have the legal right to submit that content for processing \u2014 for example, that it is publicly accessible or that you hold the necessary licence.",
      "Audia acts as an automated processor to create transformative, educational summaries of audio content. Our summaries are independent derivative works that comment on, analyse, and condense third-party material for informational and educational purposes. We believe this activity falls within the protection of the Fair Use doctrine (17 U.S.C. \u00a7 107) based on the transformative nature of the output, the informational purpose, the limited quantity reproduced, and the absence of market substitution.",
      "Audia does not host, stream, or redistribute original audio files. Transcripts are processed ephemerally and discarded after a summary is generated. Creators who wish to opt out of processing may do so via our Creator Opt-Out page.",
      "You remain solely responsible for ensuring your use of any output generated by Audia complies with applicable copyright laws in your jurisdiction.",
    ],
  },
  {
    icon: Shield,
    title: "5. Intellectual Property",
    body: [
      "All trademarks, service marks, logos, and trade names on the Service are proprietary to Audia Technologies Inc. or our licensors. Nothing in these Terms grants you any right to use them without prior written consent.",
      "AI-generated summaries produced by the Service are provided to you under a limited licence for personal, non-commercial use. You may not republish, sell, or licence summaries to third parties.",
    ],
  },
  {
    icon: Scale,
    title: "6. Disclaimer of Warranties",
    body: [
      "THE SERVICE IS PROVIDED \u201cAS IS\u201d AND \u201cAS AVAILABLE\u201d WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.",
      "We do not warrant that: (a) the Service will be uninterrupted or error-free; (b) AI-generated summaries will be accurate, complete, or free from bias; or (c) any defects will be corrected.",
    ],
  },
  {
    icon: ShieldAlert,
    title: "7. Limitation of Liability",
    body: [
      "TO THE FULLEST EXTENT PERMITTED BY LAW, AUDIA TECHNOLOGIES INC., ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING OUT OF OR RELATED TO YOUR USE OF THE SERVICE.",
      "Our total aggregate liability for any claims arising under these Terms shall not exceed the greater of (a) USD $100 or (b) the total amount you paid to Audia in the twelve (12) months immediately preceding the event giving rise to the claim.",
      "Some jurisdictions do not allow the exclusion of certain warranties or the limitation of liability. In such jurisdictions, our liability is limited to the maximum extent permitted by law.",
    ],
  },
  {
    icon: FileText,
    title: "8. Governing Law & Disputes",
    body: [
      "These Terms are governed by the laws of the State of Delaware, United States, without regard to conflict-of-law principles. Any dispute arising from these Terms shall be resolved exclusively by binding arbitration under the JAMS rules, except that either party may seek injunctive relief in a court of competent jurisdiction.",
      "YOU WAIVE YOUR RIGHT TO PARTICIPATE IN A CLASS-ACTION LAWSUIT OR CLASS-WIDE ARBITRATION.",
    ],
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0a0a0a] text-white flex flex-col">
      <nav className="flex items-center justify-between px-6 py-5 border-b border-white/5 bg-black/60 backdrop-blur-xl sticky top-0 z-50">
        <Link href="/" className="flex items-center gap-2 text-zinc-400 hover:text-white text-sm font-medium transition-colors">
          <ArrowLeft size={15} />
          Back to Home
        </Link>
        <span className="text-[11px] font-bold tracking-widest uppercase text-zinc-600">Audia \u00b7 Legal</span>
      </nav>

      <main className="flex-1 max-w-3xl mx-auto w-full px-6 py-16">
        <div className="mb-12">
          <div className="flex items-center gap-2 mb-4">
            <div className="w-8 h-8 rounded-lg bg-orange-500/10 border border-orange-500/20 flex items-center justify-center">
              <Scale size={16} className="text-orange-400" />
            </div>
            <span className="text-[11px] font-bold uppercase tracking-widest text-orange-400/80">Legal</span>
          </div>
          <h1 className="text-4xl font-extrabold tracking-tight text-white mb-3">Terms of Service</h1>
          <p className="text-zinc-500 text-sm">Last updated: May 9, 2026 \u00b7 Effective immediately for all new accounts.</p>
        </div>

        <div className="space-y-10">
          {sections.map(({ icon: Icon, title, body }) => (
            <div key={title} className="border-b border-white/5 pb-10">
              <div className="flex items-center gap-3 mb-4">
                <div className="w-7 h-7 rounded-lg bg-white/5 border border-white/10 flex items-center justify-center shrink-0">
                  <Icon size={14} className="text-zinc-400" />
                </div>
                <h2 className="text-white font-semibold text-base">{title}</h2>
              </div>
              <div className="space-y-3 pl-10">
                {body.map((para, i) => (
                  <p key={i} className="text-zinc-400 text-sm leading-relaxed">{para}</p>
                ))}
              </div>
            </div>
          ))}
        </div>

        <div className="mt-12 bg-white/[0.03] border border-white/10 rounded-2xl p-6">
          <h3 className="text-white font-semibold mb-2">Questions?</h3>
          <p className="text-zinc-500 text-sm mb-4">If you have questions about these Terms, please contact our legal team.</p>
          <a href="mailto:legal@audia.app" className="inline-flex items-center gap-2 px-5 py-2.5 bg-gradient-to-r from-[#FF7A00] to-[#E05A00] rounded-xl text-white font-semibold text-sm hover:opacity-90 transition-opacity">
            legal@audia.app
          </a>
        </div>

        <div className="mt-6 flex gap-4 text-sm">
          <Link href="/privacy" className="text-zinc-500 hover:text-white transition-colors">Privacy Policy</Link>
          <Link href="/dmca" className="text-zinc-500 hover:text-white transition-colors">DMCA Policy</Link>
          <Link href="/opt-out" className="text-zinc-500 hover:text-white transition-colors">Creator Opt-Out</Link>
        </div>
      </main>
    </div>
  );
}


export default function TermsPage() {
  const sections = [
    {
      icon: CheckCircle,
      title: "Acceptance of Terms",
      content: "By accessing or using Audia (the Service), you agree to be bound by these Terms of Service. If you disagree with any part of these terms, you may not access the Service. These terms apply to all users, including visitors, registered users, and subscribers."
    },
    {
      icon: Scale,
      title: "Use License & Restrictions",
      content: "We grant you a limited, non-exclusive, non-transferable license to use Audia for personal, non-commercial purposes. You may not: redistribute summaries for profit, attempt to reverse engineer our AI models, use automated systems to abuse our service, or resell access to your account."
    },
    {
      icon: FileText,
      title: "Content & Copyright",
      content: "Audia provides summaries of third-party content. We do not claim ownership of original podcast materials. Our AI-generated summaries are derivative works intended for personal educational use. Users are responsible for complying with copyright laws in their jurisdiction when sharing or distributing summaries."
    },
    {
      icon: AlertCircle,
      title: "Limitation of Liability",
      content: "Audia is provided as-is without warranties of any kind. We are not liable for: inaccuracies in AI-generated content, service interruptions, data loss, or damages arising from your use of summaries. Our total liability shall not exceed the amount you paid for the Service in the 12 months preceding the claim."
    }
  ];

  return (
    <main className="min-h-screen bg-[#0a0500] text-white font-sans selection:bg-orange-500/30">
      {/* Navigation */}
      <nav className="max-w-6xl mx-auto px-6 md:px-12 py-8">
        <div className="flex items-center gap-4">
          <Link 
            href="/" 
            className="flex items-center gap-2 text-orange-100/60 hover:text-white transition-colors text-sm font-medium"
          >
            <ArrowLeft size={18} />
            Back to Home
          </Link>
        </div>
      </nav>

      {/* Header */}
      <header className="max-w-4xl mx-auto px-6 md:px-12 pt-12 pb-16 text-center">
        <div className="inline-flex items-center gap-2 px-4 py-2 bg-orange-500/10 border border-orange-500/20 rounded-full text-orange-400 text-xs font-bold uppercase tracking-widest mb-6">
          <Scale size={14} />
          Legal
        </div>
        <h1 className="text-4xl md:text-6xl font-bold tracking-tight mb-6 bg-gradient-to-br from-white via-orange-100 to-orange-500/50 bg-clip-text text-transparent">
          Terms of Service
        </h1>
        <p className="text-lg text-orange-100/60 max-w-2xl mx-auto leading-relaxed">
          The rules of engagement. Please read carefully before using Audia.
        </p>
        <p className="text-sm text-orange-100/40 mt-4">Last updated: May 7, 2026</p>
      </header>

      {/* Content */}
      <section className="max-w-4xl mx-auto px-6 md:px-12 pb-24">
        <div className="grid gap-6">
          {sections.map((section, index) => (
            <div
              key={index}
              className="bg-white/5 backdrop-blur-[45px] border border-white/10 rounded-3xl p-8 md:p-10 hover:border-orange-500/30 transition-colors"
            >
              <div className="flex items-start gap-4">
                <div className="w-12 h-12 bg-gradient-to-br from-orange-400 to-orange-600 rounded-xl flex items-center justify-center flex-shrink-0 shadow-lg shadow-orange-500/20">
                  <section.icon size={24} className="text-white" />
                </div>
                <div>
                  <h2 className="text-xl font-bold mb-3">{section.title}</h2>
                  <p className="text-orange-100/70 leading-relaxed">{section.content}</p>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Additional Terms */}
        <div className="mt-12 bg-white/5 backdrop-blur-[45px] border border-white/10 rounded-3xl p-8 md:p-10">
          <h3 className="text-lg font-bold mb-6">Additional Provisions</h3>
          
          <div className="space-y-6">
            <div>
              <h4 className="font-semibold text-white mb-2">Subscription & Billing</h4>
              <p className="text-orange-100/70 text-sm leading-relaxed">
                Paid subscriptions auto-renew monthly unless cancelled. You may cancel anytime through your account settings. 
                Refunds are provided within 14 days of purchase if you are unsatisfied with the service. 
                Price changes will be communicated 30 days in advance.
              </p>
            </div>

            <div>
              <h4 className="font-semibold text-white mb-2">Termination</h4>
              <p className="text-orange-100/70 text-sm leading-relaxed">
                We reserve the right to terminate or suspend your account immediately for violations of these terms, 
                fraudulent activity, or behavior that harms other users or the service. Upon termination, 
                your right to use Audia ceases immediately.
              </p>
            </div>

            <div>
              <h4 className="font-semibold text-white mb-2">Governing Law</h4>
              <p className="text-orange-100/70 text-sm leading-relaxed">
                These terms shall be governed by the laws of the State of Delaware, United States, 
                without regard to conflict of law provisions. Any disputes shall be resolved through binding 
                arbitration in San Francisco, California.
              </p>
            </div>

            <div>
              <h4 className="font-semibold text-white mb-2">Changes to Terms</h4>
              <p className="text-orange-100/70 text-sm leading-relaxed">
                We may update these terms from time to time. We will notify users of significant changes via email 
                or in-app notification. Continued use of Audia after changes constitutes acceptance of the new terms.
              </p>
            </div>
          </div>
        </div>

        <div className="mt-8 text-center">
          <p className="text-sm text-orange-100/50">
            Questions about our terms? Contact us at{" "}
            <a href="mailto:legal@audia.app" className="text-orange-400 hover:text-orange-300 transition-colors">
              legal@audia.app
            </a>
          </p>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-white/10 bg-black/50 backdrop-blur-[45px] py-8">
        <div className="max-w-6xl mx-auto px-6 md:px-12 flex flex-col md:flex-row justify-between items-center gap-4">
          <div className="text-xl font-bold tracking-tight text-white">
            Audia<span className="text-orange-500">.</span>
          </div>
          <div className="flex gap-8 text-sm text-orange-100/50">
            <Link href="/privacy" className="hover:text-white transition-colors">Privacy</Link>
            <Link href="/terms" className="hover:text-white transition-colors">Terms</Link>
          </div>
          <p className="text-xs text-orange-100/40">© 2026 Audia Labs.</p>
        </div>
      </footer>
    </main>
  );
}
